# Generated by Django 3.1.4 on 2021-04-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
